# Generated by Django 2.0.3 on 2018-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_movierental_movieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierental',
            name='posterPathURL',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movierental',
            name='returnDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movierental',
            name='title',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
